Jfinnerty/doc update
Project-MONAI/monai-deploy-workflow-manager pull request #195
Opened 2022-07-04 08:52 UTC by JJFinnerty

Updates to WorkFlow Spec

2022-07-04 14:15 UTC, joshliberty requested changes
Added a comment regarding the context.dicom which should be changed to context.input.dicom.
In addition - export destinations also need to change - since exports are now tasks, the previous task determines whether to trigger an export, based on the conditions of the task destination - the export destination itself doesn't need the additional condition.

2022-07-04 14:15 UTC, joshliberty commented on guidelines/mwm-workflow-spec.md
>  DICOM tags are available in `context.dicom`. The reference for that object is as follows:
This needs updating

2022-07-07 13:05 UTC, JJFinnerty commented on guidelines/mwm-workflow-spec.md
>  DICOM tags are available in `context.dicom`. The reference for that object is as follows:
I've made the required updates.

2022-07-07 13:13 UTC, closed without merging

2022-07-07 13:14 UTC, JJFinnerty commented
Branch Highly Contminated with Changes I did not make.