AC-487-get-triggered-workflows-by-payload-api-endpoint
Project-MONAI/monai-deploy-workflow-manager pull request #405
Opened 2022-09-06 11:54 UTC by lillie-dae

### Description

Ability to list Workflow Instance's for a given PayloadId

### Status
**Ready**

### Types of changes
- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [x] New tests added to cover the changes.
- [x] All tests passed locally.
- [ ] [Documentation comments](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/documentation-comments) included/updated.

### Additional
**Example requests:**
http://localhost:5000/workflowinstances?payloadId=b732a1bc-aab6-45ce-a690-0ea6b9f86e17

http://localhost:5000/workflowinstances?status=created&payloadId=b732a1bc-aab6-45ce-a690-0ea6b9f86e17

http://localhost:5000/workflowinstances?status=created&payloadId=b732a1bc-aab6-45ce-a690-0ea6b9f86e17&pageSize=1000001

**Example Response:**

```json
{
    "pageNumber": 1,
    "pageSize": 2,
    "firstPage": "/workflowinstances?pageNumber=1&pageSize=2",
    "lastPage": "/workflowinstances?pageNumber=8&pageSize=2",
    "totalPages": 8,
    "totalRecords": 15,
    "nextPage": "/workflowinstances?pageNumber=2&pageSize=2",
    "previousPage": null,
    "data": [
        {
            "id": "0221291c-a994-4a7b-8ec6-42fbaa25185e",
            "ae_title": "Multi_Task_1",
            "workflow_id": "d662639b-30aa-4271-8fcf-b51e6745e72b",
            "payload_id": "b732a1bc-aab6-45ce-a690-0ea6b9f86e17",
            "start_time": "2022-09-06T09:36:03.995Z",
            "status": "Created",
            "bucket_id": "monai",
            "input_metadata": {
                "": ""
            },
            "tasks": [
                {
                    "execution_id": "da69dfb4-10bb-455d-bb6b-32d3eb5e993d",
                    "workflow_instance_id": "",
                    "task_type": "Multi_task",
                    "task_start_time": "0001-01-01T00:00:00Z",
                    "execution_stats": {},
                    "task_plugin_arguments": {},
                    "task_id": "b971c259-c3d5-4ddf-93b2-56c83fb7b474",
                    "previous_task_id": "",
                    "status": "Dispatched",
                    "reason": "None",
                    "input_artifacts": {},
                    "output_artifacts": {},
                    "output_directory": "payloadId/workflows/workflowInstanceId/executionId/",
                    "result": {},
                    "input_parameters": {},
                    "next_timeout": "0001-01-01T00:00:00Z",
                    "timeout_interval": 0
                }
            ]
        }
    ],
    "succeeded": true,
    "errors": null,
    "message": null
}

```

2022-09-06 11:57 UTC, lillie-dae commented on tests/IntegrationTests/WorkflowExecutor.IntegrationTests/Features/WorkflowInstancesApi.feature
> +    #| ?pageNumber=1&pageSize=10  | 15     | 15               |
remove commented test

2022-09-06 11:57 UTC, lillie-dae commented on tests/IntegrationTests/WorkflowExecutor.IntegrationTests/Features/WorkflowInstancesApi.feature
> +@WorkflowInstancePagination2
remove 2

2022-09-06 11:58 UTC, lillie-dae commented on tests/IntegrationTests/WorkflowExecutor.IntegrationTests/StepDefinitions/WorkflowInstancesApiStepDefinitions.cs
> +            //var request = ApiHelper.Request.RequestUri?.Query;
remove comment

2022-09-06 14:29 UTC, jackschofield23 commented
Does this support the ability to disable pagination? I think Aide need the list of workflows all in one call. This could be done with another query param

2022-09-07 11:23 UTC, neildsouth approved these changes

2022-09-07 11:54 UTC, jackschofield23 requested changes
Does this support the ability to disable pagination? I think Aide need the list of workflows all in one call. This could be done with another query param

2022-09-07 13:59 UTC, jackschofield23 approved these changes

2022-09-08 12:42 UTC, RemakingEden commented
Adding integration tests to this

2022-09-08 15:03 UTC, merged