Add Contributing guideline w/ .NET analyzer rules
Project-MONAI/monai-deploy-workflow-manager pull request #72
Opened 2022-03-29 15:35 UTC by mocsharp

- Add CONTRIBUTING.md
- Update `.editorconfig` file with .NET analyzer rules to enforce coding styles, naming conventions 
- Add CODE_OF_CONDUCT.md

2022-03-29 16:02 UTC, joshliberty requested changes

2022-03-29 16:02 UTC, joshliberty commented on CONTRIBUTING.md
> +Welcome to Project MONAI Deploy Informatics Gateway! We're excited you're here and want to contribute. This documentation is intended for individuals and institutions interested in contributing to th
@mocsharp this needs some text updates to refer to the workflow manager instead of the Informatics Gateway

2022-03-29 17:09 UTC, mocsharp commented
@joshliberty and team, please feel free to modify the rules if needed.

2022-03-30 08:12 UTC, joshliberty approved these changes

2022-03-30 18:21 UTC, merged